#!/usr/bin/perl

use strict;
use warnings;

open(hTEXTOUT, ">>", $ARGV[1]) or die "Cannot open the output file!";
chdir($ARGV[0]) or die "Cannot change directory: $!\n";

my $output = $ARGV[2];
my @files = glob("*vec");

foreach my $file (@files) {

	print "\t$file\n";
	open(hTEXTIN, $file) or die "Cannot open the input file!";
	my @content = <hTEXTIN>;
	close(hTEXTIN);

	for (@content)
	{	
		my @line = split("\t", $_); 	
		$line[1] =~ s/\n/,/;	
		print hTEXTOUT "$line[1]";
	}

	print hTEXTOUT "\"$output\"\n";
}

close(hTEXTOUT);
exit 0;
